# Generated by cucumber-sinatra. (2012-04-30 07:36:14 -0400)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/rvm_fw.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = RvmFw

class RvmFwWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  RvmFwWorld.new
end
