language: ruby
bundler_args: --without development --path=~/.bundle
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
# uncomment this line if your project needs to run something other than `rake`:
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
script: bundle exec cucumber
script: bundle exec rspec spec
